import React, { useCallback, useEffect, useState } from 'react';
import Head from 'next/head';
import Link from 'next/link';
import axiosClient from '@/libraries/axiosClient';

function Categories({ categories }) {

  return (
    <>
      <Head>
        <title>Trang danh mục sản phẩm</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {
      
          <div style={{display: 'flex', flexDirection: 'column'}}>
            {categories && categories.map((p) => <Link style={{ height: '80px' }} key={p._id} href={`/categories/${p._id}`}><h1>{p.name}</h1></Link>)}
          </div>
     
      }
    </>
  );
}

export default Categories;

// getServerSideProps - Server-Side Rendering
export async function getServerSideProps() {
  try {
    const response = await axiosClient.get('/categories');
    console.log('««««« response »»»»»', response);
    return {
      props: {
        categories: response.data.payload,
      },

      // revalidate: 24 * 60 * 60,
    };
  } catch (error) {
    return {
      notFound: true,
    };
  }
}
